name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Protocol Buffers
      run: sudo apt-get install -y protobuf-compiler
    - uses: actions/checkout@v4
    - name: Start Server
      run: nohup cargo run --bin server -- --offline & sleep 10
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose